import i18next from '../frontend/node_modules/i18next';
import { createRequire } from 'node:module';
const { getAuthorName } = createRequire(import.meta.url)('../frontend/src/utils/author.ts');
import assert from 'node:assert/strict';
import { parseBatch, normalizePage, EVENTS } from '../packages/product-analytics/src/contract';
import { summarize, type StoredEvent } from '../packages/product-analytics/src/report';
import { parseFilter } from '../packages/product-analytics/src/repository';
import { verifyPassword, passwordHash } from '../workers/admin/src/auth';
const now = Date.now();
const event = { id: crypto.randomUUID(), name: 'page_view', at: now, page: 'home' };
const batch = { visitorId: crypto.randomUUID(), sessionId: crypto.randomUUID(), device: 'desktop', referrer: 'direct', events: [event] };
assert.deepEqual(parseBatch({ ...batch, email: 'private@example.com', events: [{ ...event, code: 'secret', email: 'private@example.com' }] }), batch);
for (const invalid of [{ ...batch, events: [{ ...event, name: 'login_success' }] }, { ...batch, events: [{ ...event, dimension: 'private@example.com' }] }, { ...batch, events: Array(21).fill(event) }, { ...batch, events: [{ ...event, page: '/u/private@example.com' }] }, { ...batch, events: [{ ...event, at: now - 2 * 86400000 }] }]) assert.throws(() => parseBatch(invalid));
assert.equal(normalizePage('/u/private@example.com?secret=abc'), 'creator');
assert.equal(normalizePage('/projects/secret-id?token=abc'), 'project');
assert.throws(() => parseFilter(new URL('https://admin.test?from=2026-02-30')));
assert.throws(() => parseFilter(new URL('https://admin.test?from=2026-01-01&to=2026-03-01')));
const make = (name: StoredEvent['name'], session = 'one', at = now): StoredEvent => ({ id: crypto.randomUUID(), name, at, received_at: at, visitor_id: session, session_id: session, page: 'home', dimension: null, duration_ms: null, flow_id: name.startsWith('deployment') ? session : null, device: 'desktop', referrer: 'direct', signed_in: 0, is_admin: 0, source: EVENTS[name][2] });
const rows = [make('project_create_click'), make('project_created', 'one', now + 1), make('deployment_start', 'one', now + 2), make('deployment_success', 'one', now + 3), make('deployment_success', 'other', now + 4), make('project_created', 'wrong-order', now + 5), make('project_create_click', 'wrong-order', now + 6), make('deployment_start', 'wrong-order', now + 7)];
const report = summarize(rows);
assert.deepEqual(report.funnels.creation.map(s => s.sessions), [2, 1, 1, 1]);
assert.equal(report.deployment.succeeded, 1, 'orphan outcomes must not inflate success rate');
assert.equal(report.deployment.started, 2);
assert.equal(report.features.find(f => f.name === 'search_submit')?.events, 0);
assert.equal(summarize([]).summary.visitors, 0);
const salt = 'test-only-salt'; const hashed = await passwordHash('test-only-password', salt);
assert.equal(await verifyPassword('test-only-password', `${salt}:${hashed}`), true);
assert.equal(await verifyPassword('wrong-password', `${salt}:${hashed}`), false);
assert.equal(await verifyPassword('x', ''), false);
console.log('PASS privacy allowlist, spoofed server event rejection, route redaction, date limits, ordered funnels, matched deployment results, zero-use features and independent password authentication');

await i18next.init({ lng: 'en', resources: { en: { translation: { profile: { creator: 'Creator' } } }, zh: { translation: { profile: { creator: '创作者' } } } } });
assert.equal(getAuthorName({ id: 'internal-secret-id', displayName: 'private@example.com' }), 'Creator');
assert.equal(getAuthorName({ handle: 'jane', displayName: 'private@example.com' }), '@jane');
assert.equal(getAuthorName({ handle: 'jane', displayName: '小简 Jane' }), '小简 Jane');
await i18next.changeLanguage('zh');
assert.equal(getAuthorName({ id: 'internal-secret-id' }), '创作者');
assert.equal(getAuthorName({ displayName: '小简 Jane' }), '小简 Jane');
console.log('PASS public author fallback, no email or internal-ID label, handle and nickname consistency across languages');
